backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets/portfolio" # Media files will be stored in the repo under public/
public_folder: "/assets/portfolio" # The src attribute for uploaded media

collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/portfolio
    label: "Portfolio Items" # Used in the UI
    folder: "src/content/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Wedding", "Baby", "Travel", "Fashion", "Product", "Documentary"]}
      - {label: "Image", name: "image", widget: "image"}
